version: '3'

services:
  wp:
    image: wordpress:latest
    ports:
      - ${IP}:80:80
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./mp-challenge:/var/www/html/wp-content/plugins/mp-challenge
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
#      WORDPRESS_AUTH_KEY: ${AUTH_KEY}
#      WORDPRESS_SECURE_AUTH_KEY: ${SECURE_AUTH_KEY}
#      WORDPRESS_LOGGED_IN_KEY: ${LOGGED_IN_KEY}
#      WORDPRESS_NONCE_KEY: ${NONCE_KEY}
#      WORDPRESS_AUTH_SALT: ${AUTH_SALT}
#      WORDPRESS_SECURE_AUTH_SALT: ${SECURE_AUTH_SALT}
#      WORDPRESS_LOGGED_IN_SALT: ${LOGGED_IN_SALT}
#      WORDPRESS_NONCE_SALT: ${NONCE_SALT}
      WORDPRESS_DEBUG: ${WP_DEBUG}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_DEBUG_LOG', ${WP_DEBUG_LOG});
        define('WP_DEBUG_DISPLAY', ${WP_DEBUG_DISPLAY});
      # define('XDEBUG_CONFIG', ${XDEBUG_CONFIG});
      # XDEBUG_CONFIG = remote_host=localhost.localdomain
    depends_on:
      - db
    links:
      - db

  db:
    image: mysql:latest # mysql or mariadb
    ports:
      - ${IP}:3306:3306 # change ip if required
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
      - db_chal_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"

  wpcli:
    image: conetix/wordpress-with-wp-cli
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./mp-challenge:/var/www/html/wp-content/plugins/mp-challenge
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DEBUG: ${WP_DEBUG}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_DEBUG_LOG', ${WP_DEBUG_LOG});
        define('WP_DEBUG_DISPLAY', ${WP_DEBUG_DISPLAY});
    depends_on:
      - db
      - wp

volumes:
  db_chal_data:


